version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    env_file:
      - .env
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn aneiap_ats.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - web
